"""create_groups_table

Revision ID: 06411b8f6ba0
Revises: 60c8b765d395
Create Date: 2022-10-07 03:10:29.211950

"""
from alembic import op
import sqlalchemy as sa
from lib.util_sqlalchemy import AwareDateTime

# revision identifiers, used by Alembic.
revision = '06411b8f6ba0'
down_revision = '60c8b765d395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('created_on', AwareDateTime(), nullable=True),
    sa.Column('updated_on', AwareDateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('privacy', sa.Enum('public', 'private', name='privacy_types', native_enum=False), server_default='public', nullable=False),
    sa.Column('background', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_groups_privacy'), 'groups', ['privacy'], unique=False)
    op.create_table('group_participants',
    sa.Column('created_on', AwareDateTime(), nullable=True),
    sa.Column('updated_on', AwareDateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('fingerprint_id', sa.String(length=124), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'fingerprint_id'),
    sa.UniqueConstraint('group_id', 'user_id')
    )
    op.create_unique_constraint(None, 'post_viewed', ['post_id', 'author_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_viewed', type_='unique')
    op.drop_table('group_participants')
    op.drop_index(op.f('ix_groups_privacy'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
