"""“added_message”

Revision ID: 0df04387e584
Revises: 5856fdb42005
Create Date: 2022-04-13 16:49:12.407422

"""
from alembic import op
import sqlalchemy as sa
from lib.util_sqlalchemy import AwareDateTime


# revision identifiers, used by Alembic.
revision = '0df04387e584'
down_revision = '5856fdb42005'
branch_labels = None
depends_on = None


def upgrade():
    # ### cli auto generated by Alembic - please adjust! ###
    # op.create_table('private_chat_meta',
    # sa.Column('created_on', AwareDateTime(), nullable=True),
    # sa.Column('updated_on', AwareDateTime(), nullable=True),
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('from_user', sa.String(), nullable=True),
    # sa.Column('to_user', sa.String(), nullable=True),
    # sa.Column('room_id', sa.Integer(), nullable=True),
    # sa.Column('is_typing', sa.Boolean(), nullable=True),
    # sa.Column('is_blocked', sa.Boolean(), nullable=True),
    # sa.Column('is_favourite', sa.Boolean(), nullable=True),
    # sa.Column('is_muted', sa.Boolean(), nullable=True),
    # sa.Column('unread_count', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['from_user'], ['users.id'], ),
    # sa.ForeignKeyConstraint(['to_user'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('id')
    # )
    # op.create_table('push_devices',
    # sa.Column('created_on', AwareDateTime(), nullable=True),
    # sa.Column('updated_on', AwareDateTime(), nullable=True),
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.String(), nullable=True),
    # sa.Column('token', sa.Text(), nullable=False),
    # sa.Column('device', sa.String(length=300), nullable=True),
    # sa.Column('perm_group', sa.Integer(), nullable=False),
    # sa.Column('perm_private', sa.Integer(), nullable=False),
    # sa.Column('perm_mentions', sa.Integer(), nullable=False),
    # sa.Column('perm_notice', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('id')
    # )
    # op.create_table('private_chats',
    # sa.Column('created_on', AwareDateTime(), nullable=True),
    # sa.Column('updated_on', AwareDateTime(), nullable=True),
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('meta_id', sa.Integer(), nullable=True),
    # sa.Column('sender_id', sa.String(), nullable=True),
    # sa.Column('room_id', sa.Integer(), nullable=True),
    # sa.Column('message_type', sa.Integer(), nullable=False),
    # sa.Column('message', sa.Text(), nullable=True),
    # sa.Column('status', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['meta_id'], ['private_chat_meta.id'], ),
    # sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('id')
    # )
    # ### end Alembic cli ###
    pass


def downgrade():
    # ### cli auto generated by Alembic - please adjust! ###
    # op.drop_table('private_chats')
    # op.drop_table('push_devices')
    # op.drop_table('private_chat_meta')
    # ### end Alembic cli ###
    pass
