"""“added_external_votes”

Revision ID: 12b90ff9ed6a
Revises: 7e9501ebfc4e
Create Date: 2022-01-25 21:06:51.361239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from lib.util_sqlalchemy import AwareDateTime
# revision identifiers, used by Alembic.
revision = '12b90ff9ed6a'
down_revision = '7e9501ebfc4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### cli auto generated by Alembic - please adjust! ###
    # ### end Alembic cli ###
    pass


def downgrade():
    # ### cli auto generated by Alembic - please adjust! ###
    # ### end Alembic cli ###
    pass
