"""“longer_usernames”

Revision ID: 3a9b11fb89ec
Revises: f1ac4634b953
Create Date: 2022-03-11 05:27:08.696236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9b11fb89ec'
down_revision = 'f1ac4634b953'
branch_labels = None
depends_on = None


def upgrade():
    # ### cli auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(None, 'post_poll_reports', ['id'])
    # op.create_unique_constraint(None, 'post_viewed', ['id'])
    # ### end Alembic cli ###
    pass


def downgrade():
    # ### cli auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'post_viewed', type_='unique')
    # op.drop_constraint(None, 'post_poll_reports', type_='unique')
    # ### end Alembic cli ###
    pass
