"""“added_message_to_notifications_relationship”

Revision ID: 559d6aaefebd
Revises: 312c2044d3e1
Create Date: 2022-05-06 18:52:38.583717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559d6aaefebd'
down_revision = '312c2044d3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### cli auto generated by Alembic - please adjust! ###
    # op.add_column('notifications', sa.Column('message_content_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'notifications', 'private_chats', ['message_content_id'], ['id'])
    # ### end Alembic cli ###
    pass


def downgrade():
    # ### cli auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'notifications', type_='foreignkey')
    # op.drop_column('notifications', 'message_content_id')
    # ### end Alembic cli ###
    pass
