"""“added_user_status”

Revision ID: 5856fdb42005
Revises: 5a0b23a34776
Create Date: 2022-04-07 19:53:46.715210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5856fdb42005'
down_revision = '5a0b23a34776'
branch_labels = None
depends_on = None


def upgrade():
    # ### cli auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic cli ###
    pass


def downgrade():
    # ### cli auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'status')
    # ### end Alembic cli ###
    pass
