"""“added_report”

Revision ID: 7e9501ebfc4e
Revises: 6c97cc8995c4
Create Date: 2022-01-17 19:49:11.625258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from lib.util_sqlalchemy import AwareDateTime

# revision identifiers, used by Alembic.
revision = '7e9501ebfc4e'
down_revision = '6c97cc8995c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### cli auto generated by Alembic - please adjust! ###
    # ### end Alembic cli ###
    pass


def downgrade():
    # ### cli auto generated by Alembic - please adjust! ###
    # ### end Alembic cli ###
    pass
