"""“added_display_name”

Revision ID: ee8da81d305e
Revises: 12b90ff9ed6a
Create Date: 2022-02-09 04:41:07.377609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8da81d305e'
down_revision = '12b90ff9ed6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### cli auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic cli ###


def downgrade():
    # ### cli auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic cli ###
