"""“added_post_viewed_table”

Revision ID: f1ac4634b953
Revises: ee8da81d305e
Create Date: 2022-03-02 14:48:49.985579

"""
from alembic import op
import sqlalchemy as sa
from lib.util_sqlalchemy import AwareDateTime


# revision identifiers, used by Alembic.
revision = 'f1ac4634b953'
down_revision = 'ee8da81d305e'
branch_labels = None
depends_on = None


def upgrade():
    # ### cli auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic cli ###


def downgrade():
    # ### cli auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic cli ###
